<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class UserRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'name' => 'Regex:/^[A-Z][\D]+$/i|max:100',
            'surname' => 'Regex:/^[A-Z][\D]+$/i|max:100',
            'email' => 'email',
            'password' => 'Regex:/^(.){6,}$/',
            'adress' => 'Regex:/^[A-Z][a-zA-Z0-9\/\s]{10,}$/',
            'mobile' => 'Regex:/^[0-9]{9,15}$/'

        ];
    }

    //public function messages()
    //{
       // return [
            //"required" => "Polje :attribute je obavezno."
        //];
        //return parent::messages(); // TODO: Change the autogenerated stub
    //}
}


